![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

<center> <h1>NUMPY</h1> </center> 

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

# Descripción:

En este notebook se explicarán _NumPy_ la librería de cálculo numérico uno de los paquetes centrales para la computación numérica en Python.

# Objetivos:


 1. Familiarizarce con las matrices en NumPy
 2. Creación de matrices en Numpy
 3. Comprobar la facilidad de uso en NumPy

# Contenido:

[1. Numpy: Librería de cálculo numérico](#1.-Numpy:-Librería-de-cálculo-numérico)<br>
[2. Numpy: Funciones básicas](#2.-Numpy:-Funciones-básicas)<br>
[3. Inspeccionar matrices de NumPy](#3.-Inspeccionar-matrices-de-NumPy)<br>
[4. Operaciones Matemáticas entre matrices de NumPy](#4.-Operaciones-Matemáticas-entre-matrices-de-NumPy)<br>

[EJEMPLOS](#EJEMPLOS)<br>
[BIBLIOGRAFÍA](#BIBLIOGRAFÍA)<br>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

## <font color=#33A5FF>****1. Numpy: Librería de cálculo numérico****<tfont>

<img src="https://user-images.githubusercontent.com/19308295/115939595-32bf1300-a464-11eb-8c50-6f05dce9a805.png"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

NumPy (Numerical Python) es uno de los paquetes centrales para la computación numérica en Python. Pandas, Matplotlib, Statmodels y muchas otras librerías científicas dependen de NumPy.

Las principales contribuciones de NumPy son:

* Computación numérica eficiente con código "C"
* Recopilaciones eficientes con operaciones vectoriales
* Un Aplicativo (API) de álgebra lineal integrada y natural
* Un Aplicativo (API) en C para conectar NumPy con librerías escritas en C, C++ o FORTRAN.

Desarrollemos la eficiencia. En Python, **todo es un objeto**, lo que significa que incluso los simples __enteros (int)__ son también objetos, con toda la maquinaria necesaria para hacer que el objeto funcione. Los llamamos "Boxed Ints". En cambio, `NumPy` utiliza tipos numéricos primitivos (floats, ints) que hacen que el almacenamiento y el cálculo sean eficientes.


![Python Boxed Ints vs C and Numpy](https://user-images.githubusercontent.com/19308295/115942212-b2ea7600-a46e-11eb-86ed-d7cdc9dffbe0.png)


<img src="https://user-images.githubusercontent.com/19308295/115942590-98b19780-a470-11eb-84b0-a6390e928eb3.png"
    style="width:700px"></img>


<div class="well">

<strong>Utilización de NumPy:</strong>
    
* En Matemáticas (Reemplaza al MATLAB)
* Genera Gráficos a partir de Matrices Numpy 
* Backend (Pandas, Connect 4 Games, Fotografía Digital)
* Machine Learning.
    
</div>

<div class="well">

<strong>NumPy Array o el arreglo de matrices de NumPy</strong> es un potente objeto de matriz N-dimensional que tiene forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones de memoria. 
    
En la siguiente imagen, es una <strong>matriz bidimensiona</strong>l porque tiene filas y columnas, como puedes ver tiene cuatro filas y tres columnas, por lo que se convierte en una matriz bidimensional. En el caso de que solo tuviera una fila entonces habría sido una matriz unidimensional.
    
</div>

![Practica_04](https://user-images.githubusercontent.com/19308295/115941133-c8a96c80-a469-11eb-8e21-117c1e84bf69.png)

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****2. Numpy: Funciones básicas****<tfont>

###  Matriz  unidimensional

Con la primera instrucción `import numpy as np` le estamos indicando a nuestro programa de Python que de ahora en adelante `np` será la referencia para todo lo referente a NumPy.

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


###  Matriz bidimensional

In [3]:
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
array=np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


###  Porque usar NumPy

Porque usar NumPy en vez de utilizar las listas propias que ofrece Python para manejar estos datos, la primera razón es que NumPy ocupa menos memoria en comparación a las lista de Python, a su vez es bastante rápido en términos de ejecución. Lo que se observa en el siguiente ejemplo:

**Cantidad de memoria asignada**

In [5]:
import sys
S=range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [6]:
D=np.arange(1000)
print(D.size*D.itemsize)

8000


**Velocidad**

In [11]:
import time

SIZE =1000000

L1=range(SIZE)
L2=range(SIZE)

start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

730.5872440338135


In [12]:
A1=np.arange(SIZE)
A2=np.arange(SIZE)

start = time.time()
result = A1+A2

print((time.time()-start)*1000)

279.1097164154053


### Matrices Vacias

En ocasiones se requiere crear matrices vacías, esto se refiere a que se requieren marcadores de posición iniciales, que luego pueden ser rellenados. Se puede inicializar matrices con unos o ceros, pero también puedes hacer matrices que se llenan con valores espaciados uniformemente, valores constantes o aleatorios.

Algunas de las instrucciones para crear este tipo de matrices son las siguientes:

**Crear una matriz en donde todos los valores sean igual a 1**

In [13]:
# Crear una matriz de unos - 3 filas 4 columnas
unos = np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Crear una matriz en donde todos los valores sean igual a 0**

In [14]:
# Crear una matriz de unos - 3 filas 4 columnas
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Crear una matriz de números aleatorios**

In [15]:
aleatorios=np.random.random((2,2))
print(aleatorios)

[[0.6478163  0.09335495]
 [0.41822608 0.33658883]]


**Crear una matriz vacía**

In [18]:
vacia = np.empty((3,2))
print(vacia)

[[4.66944056e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


**Crear una matriz que contenga un solo valor en todas las posiciones**

In [17]:
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


**Crear una matriz con rangos de números**

In [19]:
espacio1 = np.arange(0,30,5)
print(espacio1)

[ 0  5 10 15 20 25]


In [20]:
espacio2 = np.linspace(0,2,5)
print(espacio2)

[0.  0.5 1.  1.5 2. ]


**Crear una matriz identidad**

In [21]:
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****3. Inspeccionar matrices de NumPy****<tfont>

**Dimensión de una matriz**

In [22]:
# Conocer las dimensiones de una matriz
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


**Tipo de Datos de una matriz**

In [23]:
# Conocer el tipo de los datos
print(a.dtype)

int64


**Tamaño y forma de una matriz**

In [24]:
# Conocer el tamaño y forma de la matriz
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


**Cambio de forma de una matriz**

In [25]:
# Cambio de forma de una matriz
a = np.array([(8,9,10),(11,12,13)])
print(a)

a = a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


**Seleccionar elemento de una matriz**

In [26]:
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [27]:
# Extraer los valores de todas las filas ubicados en la columna 3 
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****4. Operaciones Matemáticas entre matrices de NumPy****<tfont>

**Valor mínimo, máximo y la suma de una matriz**

In [28]:
# Encontrar el mínimo, máximo y la suma
a = np.array([2,45,800])
print(a.min())
print(a.max())
print(a.sum())

2
800
847


**Raiz Cuadrada y Desviación de una matriz**

In [29]:
# Calcular la raíz cuadrada y la desviación estándar
a = np.array([(1,4,81),(33,44,50)])
print(np.sqrt(a))
print(np.std(a))

[[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
27.5121185419565


**Suma, resta, multiplicación y división de dos matrices**

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****EJEMPLOS****<tfont>

___Ejemplo 1:___ Cree una matriz de 5x5 con valores 1,2,3,4 justo debajo de la diagonal:

In [31]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


___Ejemplo 2:___ Crea un vector aleatorio de tamaño 30 y encuentra el valor medio :

In [32]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4478793043208921


___Ejemplo 3:___ ¿Cómo ordenar una matriz por la enésima columna?:

In [33]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 8 5]
 [1 8 2]
 [5 9 9]]
[[3 8 5]
 [1 8 2]
 [5 9 9]]


___Ejemplo 4:___ ¿Cómo agregar un borde (lleno de 0) alrededor de una matriz existente?

In [34]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## <font color=#33A5FF>****BIBLIOGRAFÍA****<tfont>

[1] Documentación de NumPy http://docs.scipy.org/doc/numpy

[2] Travis Oliphant, "Guide to NumPy" http://csc.ucdavis.edu/~chaos/courses/nlp/Software/NumPyBook.pdf

[3] SciPy Lecture Notes http://scipy-lectures.github.io

[4] Nicolas Rougier, "100 NumPy exercises" http://www.loria.fr/~rougier/teaching/numpy.100/index.html

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)